### PR TITLE
Adding Length Frequency Plots

### PR DESCRIPTION
**Pull request by jcaracappa1**
Adds plot_length_freq() which creates a PDF of the cumulative length frequency distribution for a model run and compares it to reference catch and survey lengths as well as the parameter selectivity in harvest.prm

Example below
[length_test.pdf](https://github.com/user-attachments/files/17937161/length_test.pdf)

### CODE REVIEW

**Comment by andybeet** [comment]
We should delete the R file in the root directory. it looks like a mistake commit
Do we have catch and survey reference data sets on neus-atlantis repo? I'd like to test

**Comment by andybeet** [comment]
can you send me the input files for this so i can test please?

**Comment by jcaracappa1** [comment]
```
param.ls= get_atl_paramfiles(param.dir =  'C:/Users/joseph.caracappa/Documents/GitHub/neus-atlantis/currentVersion',
                             atl.dir='C:/Users/joseph.caracappa/Documents/GitHub/neus-atlantis/Atlantis_Runs/devplusfleets',
                             run.prefix = 'neus_output',
                             include_catch=T)

plot_length_freq(param.dir =  'C:/Users/joseph.caracappa/Documents/GitHub/neus-atlantis/currentVersion',
                 run.dir =  'C:/Users/joseph.caracappa/Documents/GitHub/neus-atlantis/Atlantis_Runs/devplusfleets',
                 run.name = 'devplusfleets',
                 catch.ref = readRDS('C:/Users/joseph.caracappa/Documents/GitHub/neus-atlantis/data/groundfish_catch_length_reference.RDS'),
                 survey.ref = readRDS('C:/Users/joseph.caracappa/Documents/GitHub/neus-atlantis/data/survdat_length_reference.RDS'),
                 ref.years = c(40,50),
                 bin.width =1,
                 out.dir = 'C:/Users/joseph.caracappa/Documents/',
                 out.name = 'length_test',
                 param.ls = param.ls,
                 speciesCodes = NULL,
                 fleetCodes = NULL
)
```

**Comment by jcaracappa1** [comment]
reference files are on the devbranch of neus-atlantis

**Pull request merged**
